### ISSUE TITLE
Librem 5 + Pinetime, some issues?

### ISSUE THREAD

**Issue by rduivenvoorde** [alexr4535/siglo#104]
Eager to see if running Siglo (from flatpack) on my Librem 5 would pair with my brand new Pinetime (1.8), I tried to pair and see if time was synced (succeed earlier via another bleutooth tool)...

- I thought starting a bleutooth connection would be best, but apparently it is not? 

- removing the bt pairing from settings, Siglo could find the InfiniTime device, but clicking it did not result in going further. Turned out I had 'Keep Paired' checked earlier. 
So: when you have Keep Paired checked checked you will NOT go to the 'update firmware' page
- very goog reproducible: uncheck it and you can go to the page, go back and check Keep Paired again and it is stuck

Seeing the watch in Siglo, it does not seem to communicate (paired but not connected), should it? Both firmware and battery show noting, and time is not updated.

Then unpairing and pairing again (Bluetooth screens are flaky on my Librem 5), and at a sudden Siglo (or bt itself?) updated time and Siglo shows me firmware version (1.8). Battery keeps showing "n/a" though, should that work?

Is there some information about what kind of communication Siglo is setting up? Or what is supposed to work or not?

Having both here, I'm happy to do some testing/helping. I think I could be able to compile it myself (??on the phone??) in case the flatpack layer is an issue...

**Comment by rduivenvoorde** [comment]
Mmm, and now having paired.. (and apparently connected), Siglo does not find my Watch anymore. Should I unpair it again (can you only disconnect it?)

Other '=issue':
 In the Siglo pair screen the 'Bluetooth settings' button does not do anything (it should probably make the bt settings dialog pop up or so?)... Again not sure if this is Phosh or Flatpack related...?

**Comment by kq98** [comment]
This is Flatpak related, the persist-pair and the bt settings button currently only work without Flatpak.

**Comment by rduivenvoorde** [comment]
@kq98 is this (easy?) fixable, or should we try to get Siglo packaged for the Librem 5 (because every Librem 5 owner, off course will have a Pinetime watch ;-) )

**Comment by kq98** [comment]
My current PR #105 should work as a Flatpak, you might want to check it out.

**Comment by okennedy** [comment]
I'm getting the same thing.  The problem appears to be a flatpak sandboxing issue:
```
Traceback (most recent call last):
  File "/app/share/siglo/siglo/window.py", line 214, in on_watches_listbox_row_activated
    subprocess.Popen(["systemctl", "--user", "start", "siglo"])
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'
```
