### ISSUE TITLE
Unable to upload resources

### ISSUE THREAD

**Issue by jjs10** [alexr4535/siglo#120]
With PineTime 1.11 release there is now a resources zip file that needs to be uploaded to get new watch faces. I am currently unable to use Siglo to upload the resources .zip file

**Comment by halivorg** [comment]
Same to me: Upload of resources zipfile shows error. Console messages:

> Downloading https://github.com/InfiniTimeOrg/InfiniTime/releases/download/1.11.0/infinitime-resources-1.11.0.zip
> ERR
> pop from empty list
> Traceback (most recent call last):
>   File "/app/share/siglo/siglo/window.py", line 298, in on_firmware_run_clicked
>     self.start_flash()
>   File "/app/share/siglo/siglo/window.py", line 313, in start_flash
>     firmware_path=binfile,
> UnboundLocalError: local variable 'binfile' referenced before assignment

Run as root (same result as user) on Ubuntu 22.04.1 64bit

**Comment by halivorg** [comment]
Having just updated Siglo to verision 0.9.9. The upload of the resources zipfile still does not work. My Pinetime runs software version 1.11.0, I am connecting from a Ubuntu workstation running Ubuntu 22.10 (kernel Linux 5.19.0-23-generic x86_64). Siglo connects to the Pinetime hassle-free. While trying to upload the resources the error messages changed sligtly from the previous Silgo version:

> File set!
> ERR
> pop from empty list
> Traceback (most recent call last):
>   File "/app/share/siglo/siglo/window.py", line 280, in firmware_run_file_clicked_cb
>     self.start_flash()
>   File "/app/share/siglo/siglo/window.py", line 313, in start_flash
>     firmware_path=binfile,
> UnboundLocalError: local variable 'binfile' referenced before assignment

Run as root with a local downloaded resources zipfile.

**Comment by h0lley** [comment]
> *Note : at the time of writing this page, [Amazfish](https://github.com/piggz/harbour-amazfish) and [ITD](https://gitea.arsenm.dev/Arsen6331/itd) have already integrated this functionality. Other companion apps will hopefully implement it soon!

https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/gettingStarted/updating-software.md

for reference, here's the commit that added uploading resources support to Amazfish:

https://github.com/piggz/harbour-amazfish/commit/d0ead243372a4c56b31557d7faa0164db8c294bb

note that it is followed up by two fixes.
