### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'

### ISSUE THREAD

**Issue by cow-killer** [alexr4535/siglo#86]
Ubuntu 20.04, trying to pair PineTime, but after selecting "Keep paired", here's the log that appears in the terminal (running the Flatpak):
```
Traceback (most recent call last):
  File "/app/share/siglo/siglo/window.py", line 209, in on_watches_listbox_row_activated
    subprocess.Popen(["systemctl", "--user", "start", "siglo"])
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'systemctl
```

I'm guessing there's one `pip` dependency I'm missing?

**Comment by kq98** [comment]
Looks like #80, "keep paired" is currently broken when Siglo is build as a Flatpak.
